# Generated by Django 4.2.5 on 2023-10-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together={('place', 'image')},
        ),
    ]
